[package]
authors = ["David Wallace Croft <david@CroftSoft.com>"]
description = "Code adapted from 'p2p chat, in rust, from scratch' by n0"
edition = "2024"
homepage = "https://www.CroftSoft.com/"
license = "MIT"
name = "iroh-prototype"
publish = false
readme = "README.md"
repository = "https://github.com/david-wallace-croft/iroh-prototype"
rust-version = "1.93.1"
version = "0.0.0-SNAPSHOT"

[dependencies]

[dev-dependencies]

[features]

[profile.dev]
debug = "line-tables-only"
